### ISSUE TITLE
Request to have a conversation with you 

### ISSUE THREAD

**Issue by Th3Samaritan** [sedaoturak/data-resources-for-materials-science#3]
Hello, thank you so much for this data collection I am a final year student studying a bachelor degree in metallurgical and materials engineering looking forward to taking a project on materials informatics using Java programming but I’d love to talk more about it with you, but I don’t know how to contact you

**Comment by Opeyemi4MaterialsInformatics** [comment]
Hello, 

We can talk more about it.
akanbiopeyemisamson@gmail.com

**Comment by Th3Samaritan** [comment]
Thank you I sent you a message already

**Comment by Th3Samaritan** [comment]
Well sorry to say but it’s the owner of the account I was referring to, although I have messaged you too

**Comment by sedaoturak** [comment]
Hi. Thanks for reaching out. You can send a message on Linkedin.
And, I'll close this issue since it's not directly related to the repo itself.
